export type FightSport =
  | "MMA"
  | "Boxing"
  | "Kickboxing"
  | "Muay Thai"
  | "Bare Knuckle"
  | "Jiu-Jitsu"
  | "Wrestling";

export type WatchAccess = "Free" | "Included" | "Subscription" | "PPV";

export type FightEvent = {
  id: string;
  sport: FightSport;
  promotion: string;
  eventName: string;
  fighters: [string, string];
  stakes: string;
  startsAt: string;
  mainCardAt?: string;
  venue: string;
  location: string;
  watch: {
    provider: string;
    access: WatchAccess;
    href: string;
    note: string;
  };
  detailsUrl: string;
  bouts: string[];
};

export const verifiedDate = "July 26, 2026";

export const fightEvents: FightEvent[] = [
  {
    id: "one-friday-fights-163",
    sport: "Muay Thai",
    promotion: "ONE",
    eventName: "ONE Friday Fights 163",
    fighters: ["Pompet Pongsuphan PK", "Nat Khat Min"],
    stakes: "Flyweight Muay Thai main event",
    startsAt: "2026-07-24T13:30:00.000Z",
    venue: "Lumpinee Stadium",
    location: "Bangkok, Thailand",
    watch: {
      provider: "Watch.ONE / Prime Video",
      access: "Free",
      href: "https://watch.onefc.com/",
      note: "Free availability varies by region",
    },
    detailsUrl:
      "https://www.onefc.com/news/full-card-revealed-for-one-friday-fights-163-on-july-24/",
    bouts: [
      "Mongkoldetlek Por Pim-on vs Utkirzhon Khamidov",
      "Brazil Aekmuangnon vs Grippen Rachanon",
      "O’Neal Thompson vs Jason Chen",
    ],
  },
  {
    id: "ufc-ankalaev-guskov",
    sport: "MMA",
    promotion: "UFC",
    eventName: "UFC Fight Night",
    fighters: ["Magomed Ankalaev", "Bogdan Guskov"],
    stakes: "Light heavyweight main event",
    startsAt: "2026-07-25T13:00:00.000Z",
    mainCardAt: "2026-07-25T16:00:00.000Z",
    venue: "Etihad Arena",
    location: "Abu Dhabi, United Arab Emirates",
    watch: {
      provider: "Paramount+",
      access: "Subscription",
      href: "https://www.ufc.com/watch/schedule",
      note: "U.S. listing; availability varies by country",
    },
    detailsUrl: "https://www.ufc.com/events",
    bouts: [
      "Magomed Ankalaev vs Bogdan Guskov",
      "Full card and bout order on UFC.com",
    ],
  },
  {
    id: "joshua-prenga",
    sport: "Boxing",
    promotion: "Matchroom",
    eventName: "The Comeback",
    fighters: ["Anthony Joshua", "Kristian Prenga"],
    stakes: "Heavyweight main event",
    startsAt: "2026-07-25T16:00:00.000Z",
    mainCardAt: "2026-07-25T20:00:00.000Z",
    venue: "Jeddah Season",
    location: "Jeddah, Saudi Arabia",
    watch: {
      provider: "DAZN",
      access: "PPV",
      href: "https://www.dazn.com/",
      note: "Worldwide DAZN pay-per-view",
    },
    detailsUrl:
      "https://www.matchroomboxing.com/news/two-world-title-fights-added-to-the-comeback-undercard-on-july-25-in-jeddah-with-hamzah-sheeraz-vs-simon-zachenhuber-and-josh-kelly-vs-caomhin-agyarko-live-worldwide-on-dazn/",
    bouts: [
      "Hamzah Sheeraz vs Simon Zachenhuber",
      "Josh Kelly vs Caoimhin Agyarko",
      "Reito Tsutsumi vs Alvino Herrera",
    ],
  },
  {
    id: "pfl-washington-dc",
    sport: "MMA",
    promotion: "PFL",
    eventName: "PFL Washington D.C.",
    fighters: ["Thad Jean", "Shamil Musaev"],
    stakes: "PFL welterweight world title",
    startsAt: "2026-07-25T23:00:00.000Z",
    mainCardAt: "2026-07-26T02:00:00.000Z",
    venue: "CareFirst Arena",
    location: "Washington, D.C.",
    watch: {
      provider: "ESPN App / ESPN",
      access: "Subscription",
      href: "https://www.espn.com/watch/",
      note: "Prelims on ESPN App; main card on ESPN in the U.S.",
    },
    detailsUrl:
      "https://pflmma.com/news/pfl-washington-dc-full-card-confirmed-for-july-31-at-carefirst-arena",
    bouts: [
      "Magomed Umalatov vs Ernesto Rodriguez",
      "Bryce Meredith vs Jack Cartwright",
      "Sullivan Cauley vs Rasul Magomedov",
    ],
  },
  {
    id: "bkfc-uruguay",
    sport: "Bare Knuckle",
    promotion: "BKFC",
    eventName: "BKFC Fight Night Uruguay",
    fighters: ["Gaston Reyno", "Josh Krejci"],
    stakes: "Bare-knuckle main event",
    startsAt: "2026-07-25T23:00:00.000Z",
    venue: "Antel Arena",
    location: "Montevideo, Uruguay",
    watch: {
      provider: "BKFC+ / Fubo Sports",
      access: "Subscription",
      href: "https://watch.bkfc.com/",
      note: "Official BKFC stream; regional options may vary",
    },
    detailsUrl: "https://www.bkfc.com/events",
    bouts: ["Gaston “Tonga” Reyno vs Josh Krejci"],
  },
  {
    id: "u17-wrestling-worlds-2026",
    sport: "Wrestling",
    promotion: "UWW",
    eventName: "U17 World Championships",
    fighters: ["U.S. U17 team", "International field"],
    stakes: "Greco-Roman, women's freestyle, and men's freestyle world titles",
    startsAt: "2026-07-27T06:30:00.000Z",
    venue: "Baku Sports Palace",
    location: "Baku, Azerbaijan",
    watch: {
      provider: "FloWrestling",
      access: "Subscription",
      href: "https://www.flowrestling.org/events/15687394-2026-u17-world-championships",
      note: "Live coverage and replays; regional availability may vary",
    },
    detailsUrl:
      "https://www.flowrestling.org/articles/16081156-2026-u17-us-world-championships-rosters-schedule",
    bouts: [
      "Greco-Roman: July 27-29",
      "Women's freestyle divisions",
      "Men's freestyle divisions",
    ],
  },
  {
    id: "one-friday-fights-164",
    sport: "Muay Thai",
    promotion: "ONE",
    eventName: "ONE Friday Fights 164",
    fighters: ["Card", "To be announced"],
    stakes: "Muay Thai and MMA from Lumpinee",
    startsAt: "2026-07-31T11:30:00.000Z",
    venue: "Lumpinee Stadium",
    location: "Bangkok, Thailand",
    watch: {
      provider: "Watch.ONE / Prime Video",
      access: "Free",
      href: "https://watch.onefc.com/",
      note: "Free availability varies by region",
    },
    detailsUrl: "https://www.onefc.com/events/",
    bouts: ["Full card pending official announcement"],
  },
  {
    id: "pfl-new-york",
    sport: "MMA",
    promotion: "PFL",
    eventName: "PFL New York",
    fighters: ["Usman Nurmagomedov", "Archie Colgan"],
    stakes: "PFL lightweight world title",
    startsAt: "2026-07-31T20:00:00.000Z",
    mainCardAt: "2026-07-31T23:00:00.000Z",
    venue: "UBS Arena",
    location: "Belmont Park, New York",
    watch: {
      provider: "ESPN App / ESPN",
      access: "Subscription",
      href: "https://www.espn.com/watch/",
      note: "Prelims on ESPN App; main card on ESPN in the U.S.",
    },
    detailsUrl: "https://pflmma.com/event/pfl-ny-2026",
    bouts: [
      "Dakota Ditcheva vs Denise Kielholtz",
      "More bouts on the official PFL card",
    ],
  },
  {
    id: "bjj-stars-19",
    sport: "Jiu-Jitsu",
    promotion: "BJJ Stars",
    eventName: "BJJ Stars 19: World Cup",
    fighters: ["Patricky Pitbull", "Renato Moicano"],
    stakes: "Masters Grand Prix and professional superfights",
    startsAt: "2026-07-31T23:40:00.000Z",
    venue: "Vibra S\u00e3o Paulo",
    location: "S\u00e3o Paulo, Brazil",
    watch: {
      provider: "FloGrappling",
      access: "Subscription",
      href: "https://www.flograppling.com/events/15906495-2026-bjj-stars-19",
      note: "Live stream and replay with a FloGrappling subscription",
    },
    detailsUrl: "https://bjjstars.tv/",
    bouts: [
      "Patricky Pitbull vs Renato Moicano",
      "James Ortiz vs Nicholas Vieira",
      "Masters Grand Prix bracket",
    ],
  },
  {
    id: "ufc-medic-rodriguez",
    sport: "MMA",
    promotion: "UFC",
    eventName: "UFC Fight Night Belgrade",
    fighters: ["Uroš Medić", "Daniel Rodriguez"],
    stakes: "Welterweight main event",
    startsAt: "2026-08-01T14:00:00.000Z",
    mainCardAt: "2026-08-01T17:00:00.000Z",
    venue: "Belgrade Arena",
    location: "Belgrade, Serbia",
    watch: {
      provider: "Paramount+",
      access: "Subscription",
      href: "https://www.ufc.com/watch/schedule",
      note: "U.S. listing; availability varies by country",
    },
    detailsUrl:
      "https://www.ufc.com/event/ufc-fight-night-august-01-2026",
    bouts: [
      "Jan Błachowicz vs Navajo Stirling",
      "Aleksandar Rakić vs Marcin Tybura",
      "Ludovit Klein vs Tofiq Musayev",
    ],
  },
  {
    id: "bkfc-newcastle",
    sport: "Bare Knuckle",
    promotion: "BKFC",
    eventName: "BKFC Fight Night Newcastle",
    fighters: ["Lewis Garside", "Bradley Taylor"],
    stakes: "Bare-knuckle main event",
    startsAt: "2026-08-01T18:00:00.000Z",
    venue: "Walker Activity Dome",
    location: "Newcastle, United Kingdom",
    watch: {
      provider: "BKFC+ / Fubo Sports",
      access: "Subscription",
      href: "https://watch.bkfc.com/",
      note: "Official BKFC stream; regional options may vary",
    },
    detailsUrl: "https://www.bkfc.com/events",
    bouts: ["Lewis Garside vs Bradley Taylor"],
  },
  {
    id: "pfl-charlotte",
    sport: "MMA",
    promotion: "PFL",
    eventName: "PFL Charlotte",
    fighters: ["Bryan Battle", "Dalton Rosta"],
    stakes: "Middleweight main event",
    startsAt: "2026-08-07T23:00:00.000Z",
    mainCardAt: "2026-08-08T02:00:00.000Z",
    venue: "Bojangles Coliseum",
    location: "Charlotte, North Carolina",
    watch: {
      provider: "ESPN App / ESPN",
      access: "Subscription",
      href: "https://www.espn.com/watch/",
      note: "Main card on ESPN in the U.S.",
    },
    detailsUrl:
      "https://pflmma.com/index.php/news/middleweight-matchups-headline-pfls-return-to-charlotte-on-august-7",
    bouts: [
      "Josh Silveira vs Aaron Jeffery",
      "More bouts on the official PFL card",
    ],
  },
  {
    id: "ufc-gamrot-salkilld",
    sport: "MMA",
    promotion: "UFC",
    eventName: "UFC Fight Night",
    fighters: ["Mateusz Gamrot", "Quillan Salkilld"],
    stakes: "Lightweight main event",
    startsAt: "2026-08-08T18:00:00.000Z",
    mainCardAt: "2026-08-08T21:00:00.000Z",
    venue: "Meta APEX",
    location: "Las Vegas, Nevada",
    watch: {
      provider: "Paramount+",
      access: "Subscription",
      href: "https://www.ufc.com/watch/schedule",
      note: "U.S. listing; availability varies by country",
    },
    detailsUrl: "https://www.ufc.com/events",
    bouts: ["Full card and bout order on UFC.com"],
  },
  {
    id: "bkfc-sturgis",
    sport: "Bare Knuckle",
    promotion: "BKFC",
    eventName: "BKFC Fight Night Sturgis",
    fighters: ["Bryant Acheson", "Mike Jones"],
    stakes: "Bare-knuckle main event",
    startsAt: "2026-08-09T01:00:00.000Z",
    venue: "The Buffalo Chip",
    location: "Sturgis, South Dakota",
    watch: {
      provider: "BKFC+ / Fubo Sports",
      access: "Subscription",
      href: "https://watch.bkfc.com/",
      note: "Official BKFC stream; regional options may vary",
    },
    detailsUrl: "https://www.bkfc.com/events",
    bouts: ["Bryant Acheson vs Mike Jones"],
  },
  {
    id: "one-fight-night-46",
    sport: "Muay Thai",
    promotion: "ONE",
    eventName: "ONE Fight Night 46",
    fighters: ["Stella Hemetsberger", "Natalia Diachkova"],
    stakes: "ONE strawweight Muay Thai world title",
    startsAt: "2026-08-15T01:00:00.000Z",
    venue: "Lumpinee Stadium",
    location: "Bangkok, Thailand",
    watch: {
      provider: "Prime Video",
      access: "Included",
      href: "https://www.primevideo.com/",
      note: "Included with Prime in the U.S. and Canada",
    },
    detailsUrl: "https://www.onefc.com/events/onefightnight46/",
    bouts: [
      "Stella Hemetsberger vs Natalia Diachkova",
      "Nico Carrillo makes his kickboxing debut",
    ],
  },
  {
    id: "ufc-330",
    sport: "MMA",
    promotion: "UFC",
    eventName: "UFC 330",
    fighters: ["Islam Makhachev", "Ian Machado Garry"],
    stakes: "UFC championship main event",
    startsAt: "2026-08-15T21:00:00.000Z",
    mainCardAt: "2026-08-16T01:00:00.000Z",
    venue: "Xfinity Mobile Arena",
    location: "Philadelphia, Pennsylvania",
    watch: {
      provider: "Paramount+",
      access: "Subscription",
      href: "https://www.ufc.com/watch/schedule",
      note: "Early prelims and prelims precede the main card",
    },
    detailsUrl: "https://www.ufc.com/events",
    bouts: ["Full card and bout order on UFC.com"],
  },
  {
    id: "bkfc-mohegan-sun",
    sport: "Bare Knuckle",
    promotion: "BKFC",
    eventName: "BKFC Fight Night Mohegan Sun",
    fighters: ["Bryce Henry", "Carlos Trinidad"],
    stakes: "Bare-knuckle main event",
    startsAt: "2026-08-21T22:00:00.000Z",
    venue: "Mohegan Sun",
    location: "Uncasville, Connecticut",
    watch: {
      provider: "BKFC+ / Fubo Sports",
      access: "Subscription",
      href: "https://watch.bkfc.com/",
      note: "Official BKFC stream; regional options may vary",
    },
    detailsUrl: "https://www.bkfc.com/events",
    bouts: ["Bryce Henry vs Carlos Trinidad"],
  },
  {
    id: "ufc-hernandez-rodrigues",
    sport: "MMA",
    promotion: "UFC",
    eventName: "UFC Fight Night Sacramento",
    fighters: ["Anthony Hernandez", "Gregory Rodrigues"],
    stakes: "Middleweight main event",
    startsAt: "2026-08-22T21:00:00.000Z",
    mainCardAt: "2026-08-23T00:00:00.000Z",
    venue: "Golden 1 Center",
    location: "Sacramento, California",
    watch: {
      provider: "Paramount+",
      access: "Subscription",
      href: "https://www.ufc.com/watch/schedule",
      note: "U.S. listing; availability varies by country",
    },
    detailsUrl: "https://www.ufc.com/events",
    bouts: ["Full card and bout order on UFC.com"],
  },
  {
    id: "one-friday-fights-165",
    sport: "Muay Thai",
    promotion: "ONE",
    eventName: "ONE Friday Fights 165 + Inner Circle 25",
    fighters: ["Abdulla Dayakaev", "Superlek"],
    stakes: "Bantamweight Muay Thai headliner",
    startsAt: "2026-08-07T11:30:00.000Z",
    venue: "Lumpinee Stadium",
    location: "Bangkok, Thailand",
    watch: {
      provider: "Live.ONE / ONE YouTube",
      access: "Free",
      href: "https://live.onefc.com/",
      note: "Friday Fights is free in supported regions; Inner Circle access may differ",
    },
    detailsUrl: "https://www.onefc.com/events/one-friday-fights-165/",
    bouts: [
      "Abdulla Dayakaev vs Superlek",
      "Marat Grigorian vs Mamuka Usubyan",
      "Nabil Anane vs Suakim Pongsuphan PK",
    ],
  },
  {
    id: "one-samurai-2",
    sport: "Kickboxing",
    promotion: "ONE",
    eventName: "ONE SAMURAI 2",
    fighters: ["Masaaki Noiri", "Liu Mengyang"],
    stakes: "Featherweight kickboxing tournament quarterfinal",
    startsAt: "2026-08-08T08:00:00.000Z",
    venue: "EBARA WAVE Arena Ota",
    location: "Tokyo, Japan",
    watch: {
      provider: "Live.ONE",
      access: "Subscription",
      href: "https://live.onefc.com/",
      note: "Official worldwide stream; U-NEXT carries the event in Japan",
    },
    detailsUrl: "https://www.onefc.com/events/one-samurai-2/",
    bouts: [
      "Masaaki Noiri vs Liu Mengyang",
      "Kaito Ono vs Mohammad Siasarani",
      "Kosuke Takagi vs Luo Chao",
      "Keito Yamakita vs Koyuru Tanoue",
      "Ayumu Yamamoto vs Ryo Hirayama",
      "Shoma Okumura vs Reiji Takaki",
      "Subaru Mori vs Yusuke Sato",
      "Hiroki Kasahara vs Ryuto Shiokawa",
      "Ranma vs Katsuki Kitano",
      "Suarek Rukkukamui vs Yuri Tanaka",
    ],
  },
  {
    id: "one-friday-fights-166",
    sport: "Muay Thai",
    promotion: "ONE",
    eventName: "ONE Friday Fights 166 + Inner Circle 26",
    fighters: ["Card", "To be announced"],
    stakes: "Muay Thai and MMA from Lumpinee",
    startsAt: "2026-08-14T11:30:00.000Z",
    venue: "Lumpinee Stadium",
    location: "Bangkok, Thailand",
    watch: {
      provider: "Live.ONE / ONE YouTube",
      access: "Free",
      href: "https://live.onefc.com/",
      note: "Friday Fights is free in supported regions; Inner Circle access may differ",
    },
    detailsUrl: "https://www.onefc.com/events/one-friday-fights-166/",
    bouts: ["More fights to be announced by ONE"],
  },
  {
    id: "one-friday-fights-167",
    sport: "Muay Thai",
    promotion: "ONE",
    eventName: "ONE Friday Fights 167 + Inner Circle 27",
    fighters: ["Card", "To be announced"],
    stakes: "Muay Thai and MMA from Lumpinee",
    startsAt: "2026-08-21T11:30:00.000Z",
    venue: "Lumpinee Stadium",
    location: "Bangkok, Thailand",
    watch: {
      provider: "Live.ONE / ONE YouTube",
      access: "Free",
      href: "https://live.onefc.com/",
      note: "Friday Fights is free in supported regions; Inner Circle access may differ",
    },
    detailsUrl: "https://www.onefc.com/events/one-friday-fights-167/",
    bouts: ["More fights to be announced by ONE"],
  },
  {
    id: "one-friday-fights-168",
    sport: "Muay Thai",
    promotion: "ONE",
    eventName: "ONE Friday Fights 168 + Inner Circle 28",
    fighters: ["Card", "To be announced"],
    stakes: "Muay Thai and MMA from Lumpinee",
    startsAt: "2026-08-28T11:30:00.000Z",
    venue: "Lumpinee Stadium",
    location: "Bangkok, Thailand",
    watch: {
      provider: "Live.ONE / ONE YouTube",
      access: "Free",
      href: "https://live.onefc.com/",
      note: "Friday Fights is free in supported regions; Inner Circle access may differ",
    },
    detailsUrl: "https://www.onefc.com/events/one-friday-fights-168/",
    bouts: ["More fights to be announced by ONE"],
  },
  {
    id: "one-friday-fights-169",
    sport: "Muay Thai",
    promotion: "ONE",
    eventName: "ONE Friday Fights 169 + Inner Circle 29",
    fighters: ["Card", "To be announced"],
    stakes: "Muay Thai and MMA from Lumpinee",
    startsAt: "2026-09-04T11:30:00.000Z",
    venue: "Lumpinee Stadium",
    location: "Bangkok, Thailand",
    watch: {
      provider: "Live.ONE / ONE YouTube",
      access: "Free",
      href: "https://live.onefc.com/",
      note: "Friday Fights is free in supported regions; Inner Circle access may differ",
    },
    detailsUrl: "https://www.onefc.com/events/one-friday-fights-169/",
    bouts: ["More fights to be announced by ONE"],
  },
  {
    id: "one-fight-night-47",
    sport: "MMA",
    promotion: "ONE",
    eventName: "ONE Fight Night 47",
    fighters: ["Card", "To be announced"],
    stakes: "U.S. primetime mixed-discipline card",
    startsAt: "2026-09-05T01:00:00.000Z",
    venue: "Lumpinee Stadium",
    location: "Bangkok, Thailand",
    watch: {
      provider: "Prime Video",
      access: "Included",
      href: "https://www.primevideo.com/",
      note: "Included with Prime in the U.S. and Canada",
    },
    detailsUrl: "https://www.onefc.com/events/onefightnight47/",
    bouts: ["Full lineup pending ONE's official announcement"],
  },
  {
    id: "pfl-tampa",
    sport: "MMA",
    promotion: "PFL",
    eventName: "PFL Tampa",
    fighters: ["Cris Cyborg", "Ketlen Vieira"],
    stakes: "PFL women's featherweight world title and Cyborg's final MMA fight",
    startsAt: "2026-08-22T23:00:00.000Z",
    mainCardAt: "2026-08-23T02:00:00.000Z",
    venue: "Benchmark International Arena",
    location: "Tampa, Florida",
    watch: {
      provider: "ESPN App / ESPN",
      access: "Subscription",
      href: "https://www.espn.com/watch/",
      note: "Early card on ESPN App; main card on ESPN in the U.S.",
    },
    detailsUrl: "https://pflmma.com/event/pfl-tampa",
    bouts: [
      "Cris Cyborg vs Ketlen Vieira",
      "More bouts pending PFL's official announcement",
    ],
  },
  {
    id: "liddard-morello",
    sport: "Boxing",
    promotion: "Matchroom",
    eventName: "Liddard vs Morello",
    fighters: ["George Liddard", "Dario Morello"],
    stakes: "European middleweight title",
    startsAt: "2026-08-22T18:00:00.000Z",
    venue: "York Hall",
    location: "London, United Kingdom",
    watch: {
      provider: "DAZN",
      access: "Subscription",
      href: "https://www.dazn.com/",
      note: "Live worldwide on DAZN",
    },
    detailsUrl: "https://www.matchroomboxing.com/events/liddard-vs-morello/",
    bouts: [
      "George Liddard vs Dario Morello",
      "Jimmy Sains vs Tom Cowling",
      "Emmanuel Buttigieg vs PA Gordon",
      "Tiah Mai Ayton vs Ellie Hellewell",
      "Pat McCormack vs opponent to be announced",
    ],
  },
  {
    id: "marksman-barreto",
    sport: "Boxing",
    promotion: "Matchroom",
    eventName: "Marksman vs Barreto",
    fighters: ["Corey Marksman", "Christian Barreto"],
    stakes: "Lightweight main event",
    startsAt: "2026-08-28T21:00:00.000Z",
    venue: "Caribe Royale",
    location: "Orlando, Florida",
    watch: {
      provider: "DAZN",
      access: "Subscription",
      href: "https://www.dazn.com/",
      note: "Live worldwide on DAZN",
    },
    detailsUrl: "https://www.matchroomboxing.com/events/marksman-vs-barreto/",
    bouts: [
      "Corey Marksman vs Christian Barreto",
      "Carlos De Leon vs Maxwell Montes",
      "Kapio Gallegos vs Desmond Lyons",
      "Alex Bray vs Antraveous Ingram",
    ],
  },
  {
    id: "ruiz-knyba",
    sport: "Boxing",
    promotion: "Matchroom",
    eventName: "Ruiz Jr. vs Knyba",
    fighters: ["Andy Ruiz Jr.", "Damian Knyba"],
    stakes: "Heavyweight main event",
    startsAt: "2026-09-04T22:15:00.000Z",
    venue: "Prudential Center",
    location: "Newark, New Jersey",
    watch: {
      provider: "DAZN",
      access: "Subscription",
      href: "https://www.dazn.com/",
      note: "Live worldwide on DAZN",
    },
    detailsUrl: "https://www.matchroomboxing.com/events/ruiz-jr-vs-knyba/",
    bouts: [
      "Andy Ruiz Jr. vs Damian Knyba",
      "Vito Mielnicki Jr. vs Austin Williams",
      "Alan Chaves vs Eridson Garcia",
    ],
  },
  {
    id: "taylor-pili",
    sport: "Boxing",
    promotion: "Matchroom",
    eventName: "Taylor vs Pili",
    fighters: ["Katie Taylor", "Flora Pili"],
    stakes: "Undisputed super lightweight world championship",
    startsAt: "2026-09-05T15:00:00.000Z",
    venue: "Croke Park",
    location: "Dublin, Ireland",
    watch: {
      provider: "DAZN",
      access: "Subscription",
      href: "https://www.dazn.com/",
      note: "Live worldwide on DAZN",
    },
    detailsUrl: "https://www.matchroomboxing.com/events/taylor-vs-pili/",
    bouts: [
      "Katie Taylor vs Flora Pili",
      "Dave Allen vs Thomas Carty",
      "Paddy Donovan vs Tyrone McKenna",
      "Taylor Bevan vs Emmet Brennan",
      "Joe McGrail vs Matthew Boreland",
      "Molly McCann vs Sylwia Doligala",
      "Paul Ryan vs Paddy Gallagher",
    ],
  },
  {
    id: "hedges-brown",
    sport: "Boxing",
    promotion: "Matchroom",
    eventName: "Hedges vs Brown",
    fighters: ["John Hedges", "Pat Brown"],
    stakes: "British, Commonwealth and international cruiserweight titles",
    startsAt: "2026-09-19T16:00:00.000Z",
    venue: "Co-op Live",
    location: "Manchester, United Kingdom",
    watch: {
      provider: "DAZN",
      access: "Subscription",
      href: "https://www.dazn.com/",
      note: "Live worldwide on DAZN",
    },
    detailsUrl: "https://www.matchroomboxing.com/events/hedges-vs-brown/",
    bouts: ["John Hedges vs Pat Brown", "More bouts to be announced by Matchroom"],
  },
  {
    id: "whittaker-wallace",
    sport: "Boxing",
    promotion: "Matchroom",
    eventName: "Whittaker vs Wallace",
    fighters: ["Ben Whittaker", "Conor Wallace"],
    stakes: "Light heavyweight main event",
    startsAt: "2026-10-03T15:00:00.000Z",
    venue: "Utilita Arena",
    location: "Birmingham, United Kingdom",
    watch: {
      provider: "DAZN",
      access: "Subscription",
      href: "https://www.dazn.com/",
      note: "Live worldwide on DAZN",
    },
    detailsUrl: "https://www.matchroomboxing.com/events/whittaker-vs-wallace/",
    bouts: ["Ben Whittaker vs Conor Wallace", "More bouts to be announced by Matchroom"],
  },
  {
    id: "bkfc-92-boston",
    sport: "Bare Knuckle",
    promotion: "BKFC",
    eventName: "BKFC 92 Boston",
    fighters: ["Tyler Stewart", "Joe Gigliotti"],
    stakes: "Bare-knuckle main event",
    startsAt: "2026-08-29T22:00:00.000Z",
    venue: "Fenway Park",
    location: "Boston, Massachusetts",
    watch: {
      provider: "BKFC+ / Fubo Sports",
      access: "Subscription",
      href: "https://watch.bkfc.com/",
      note: "Official BKFC stream; regional options may vary",
    },
    detailsUrl: "https://www.bkfc.com/events",
    bouts: ["Tyler Stewart vs Joe Gigliotti", "Full card on BKFC.com"],
  },
  {
    id: "bkfc-93-hollywood",
    sport: "Bare Knuckle",
    promotion: "BKFC",
    eventName: "BKFC 93 Hollywood",
    fighters: ["Leonardo Perdomo", "Isaac Garrett"],
    stakes: "Bare-knuckle main event",
    startsAt: "2026-09-11T23:00:00.000Z",
    venue: "Hard Rock Hotel & Casino",
    location: "Hollywood, Florida",
    watch: {
      provider: "BKFC+ / Fubo Sports",
      access: "Subscription",
      href: "https://watch.bkfc.com/",
      note: "Official BKFC stream; regional options may vary",
    },
    detailsUrl: "https://www.bkfc.com/events",
    bouts: ["Leonardo Perdomo vs Isaac Garrett", "Full card on BKFC.com"],
  },
  {
    id: "bkfc-94-manchester",
    sport: "Bare Knuckle",
    promotion: "BKFC",
    eventName: "BKFC 94 Manchester",
    fighters: ["Card", "To be announced"],
    stakes: "Bare-knuckle card",
    startsAt: "2026-09-26T18:00:00.000Z",
    venue: "AO Arena",
    location: "Manchester, United Kingdom",
    watch: {
      provider: "BKFC+ / Fubo Sports",
      access: "Subscription",
      href: "https://watch.bkfc.com/",
      note: "Official BKFC stream; regional options may vary",
    },
    detailsUrl: "https://www.bkfc.com/events/bkfc-94-manchester",
    bouts: ["Fights to be announced by BKFC"],
  },
  {
    id: "bkfc-belgrade",
    sport: "Bare Knuckle",
    promotion: "BKFC",
    eventName: "BKFC Fight Night Belgrade",
    fighters: ["James Faulkner", "Vaso Prasovic"],
    stakes: "Bare-knuckle main event",
    startsAt: "2026-10-17T17:00:00.000Z",
    venue: "TBA",
    location: "Belgrade, Serbia",
    watch: {
      provider: "BKFC+ / Fubo Sports",
      access: "Subscription",
      href: "https://watch.bkfc.com/",
      note: "Official BKFC stream; regional options may vary",
    },
    detailsUrl: "https://www.bkfc.com/events",
    bouts: ["James Faulkner vs Vaso Prasovic", "Full card on BKFC.com"],
  },
  {
    id: "bkfc-95-newark",
    sport: "Bare Knuckle",
    promotion: "BKFC",
    eventName: "BKFC 95 Newark",
    fighters: ["Card", "To be announced"],
    stakes: "Bare-knuckle card",
    startsAt: "2026-10-18T00:00:00.000Z",
    venue: "TBA",
    location: "Newark, New Jersey",
    watch: {
      provider: "BKFC+ / Fubo Sports",
      access: "Subscription",
      href: "https://watch.bkfc.com/",
      note: "Official BKFC stream; regional options may vary",
    },
    detailsUrl: "https://www.bkfc.com/events",
    bouts: ["Fights to be announced by BKFC"],
  },
  {
    id: "ufc-paris-september-2026",
    sport: "MMA",
    promotion: "UFC",
    eventName: "UFC Fight Night Paris",
    fighters: ["Card", "To be announced"],
    stakes: "UFC Fight Night card",
    startsAt: "2026-09-05T16:00:00.000Z",
    mainCardAt: "2026-09-05T19:00:00.000Z",
    venue: "Accor Arena",
    location: "Paris, France",
    watch: {
      provider: "Paramount+",
      access: "Subscription",
      href: "https://www.ufc.com/watch/schedule",
      note: "U.S. listing; availability varies by country",
    },
    detailsUrl: "https://www.ufc.com/event/ufc-fight-night-september-05-2026",
    bouts: ["Full card pending UFC's official announcement"],
  },
  {
    id: "noche-ufc-2026",
    sport: "MMA",
    promotion: "UFC",
    eventName: "Noche UFC",
    fighters: ["Card", "To be announced"],
    stakes: "Noche UFC card",
    startsAt: "2026-09-12T21:00:00.000Z",
    venue: "Desert Diamond Arena",
    location: "Glendale, Arizona",
    watch: {
      provider: "Paramount+",
      access: "Subscription",
      href: "https://www.ufc.com/watch/schedule",
      note: "U.S. listing; availability varies by country",
    },
    detailsUrl: "https://www.ufc.com/event/ufc-fight-night-september-12-2026",
    bouts: ["Full card pending UFC's official announcement"],
  },
  {
    id: "ufc-edmonton-october-2026",
    sport: "MMA",
    promotion: "UFC",
    eventName: "UFC Fight Night Edmonton",
    fighters: ["Card", "To be announced"],
    stakes: "UFC Fight Night card",
    startsAt: "2026-10-17T20:00:00.000Z",
    mainCardAt: "2026-10-17T22:00:00.000Z",
    venue: "Rogers Place",
    location: "Edmonton, Alberta",
    watch: {
      provider: "Paramount+",
      access: "Subscription",
      href: "https://www.ufc.com/watch/schedule",
      note: "U.S. listing; availability varies by country",
    },
    detailsUrl: "https://www.ufc.com/event/ufc-fight-night-october-17-2026",
    bouts: ["Full card pending UFC's official announcement"],
  },
  {
    id: "bkfc-clearwater-october-2026",
    sport: "Bare Knuckle",
    promotion: "BKFC",
    eventName: "BKFC Fight Night Clearwater",
    fighters: ["Card", "To be announced"],
    stakes: "Bare-knuckle card",
    startsAt: "2026-10-24T00:00:00.000Z",
    venue: "TBA",
    location: "Clearwater, Florida",
    watch: {
      provider: "BKFC+ / Fubo Sports",
      access: "Subscription",
      href: "https://watch.bkfc.com/",
      note: "Official BKFC stream; regional options may vary",
    },
    detailsUrl: "https://www.bkfc.com/events",
    bouts: ["Fights to be announced by BKFC"],
  },
  {
    id: "bkfc-glasgow-november-2026",
    sport: "Bare Knuckle",
    promotion: "BKFC",
    eventName: "BKFC Fight Night Glasgow",
    fighters: ["Card", "To be announced"],
    stakes: "Bare-knuckle card",
    startsAt: "2026-11-07T18:00:00.000Z",
    venue: "TBA",
    location: "Glasgow, United Kingdom",
    watch: {
      provider: "BKFC+ / Fubo Sports",
      access: "Subscription",
      href: "https://watch.bkfc.com/",
      note: "Official BKFC stream; regional options may vary",
    },
    detailsUrl: "https://www.bkfc.com/events",
    bouts: ["Fights to be announced by BKFC"],
  },
];
